### PR TITLE
Resolves #44 - Cope with removing properties from entities which might be null

### LINKED ISSUE #44: RFC: Using a callback with remove option
## What?
I would like to be able to use a callback function in the `remove` option, like in `set`.

```php
$this->addBehavior('Duplicatable.Duplicatable', [
    'finder' => 'complete',
    'remove' => [
        'created',
        'parts.created',
        'parts.script_id',
        'parts.slot.created',
        'parts.slot.contents.script_id', // TODO: 'contents' might be null for a slot without a block
    ],
    'set' => [
        'status_id' => 2,
    ],
    'append' => ['name' => ' - copy'],
]);
```

## Why?
In some instances of nested associations, there can be optionally empty properties, which might still need a field removing if they exist.

In the above behaviour configuration example the `contents` property might be `null` meaning that there is no `script_id` to remove.

With the current code, this creates an exception.
`Warning (2): Invalid argument supplied for foreach() [ROOT/vendor/riesenia/cakephp-duplicatable/src/Model/Behavior/DuplicatableBehavior.php, line 269]` [line 269](https://github.com/riesenia/cakephp-duplicatable/blob/master/src/Model/Behavior/DuplicatableBehavior.php#L269)

I think this is because the property is null, so the code cannot iterate the fields in the property to remove.

## How?
I propose that the callback returns a boolean if the remove should be executed or not.

```php
'remove' => [
    'created',
    'parts.created',
    'parts.script_id',
    'parts.slot.created',
    'parts.slot.contents.script_id' => function (Entity $entity) {
        return $entity->get('contents') !== null;
    }, 
],
```

### PR DESCRIPTION
**Pull request by davidyell**
Added a test case and a fix for duplicating entities with removing a property when the association might be null.

By checking if the entity is null before trying to action the property, this prevents an exception in the foreach.

I have added a fixture for testing this use-case, which meant I had to change an existing test assertion, as it was asserting that the auto-incrementing id's would match, which is no longer possible with a third invoice. Hope this is okay.

I also took the liberty of adding an `@property` tag to the test-case for ease of auto-completion.

### CODE REVIEW

**Comment by davidyell** [comment]
Let me know if you want me to fix the PHPCS issues with the files or not

File: src/Model/Behavior/DuplicatableBehavior.php [hunk 1]
```diff
@@ -266,8 +266,10 @@ protected function _drillDownEntity($action, EntityInterface $entity, array $par
             return;
         }
 
-        foreach ($entity->{$prop} as $key => $e) {
-            $this->_drillDownEntity($action, $e, $parts, $value);
+        if ($entity->{$prop} !== null) {
```
Comment (ADmad) [inline src/Model/Behavior/DuplicatableBehavior.php]: `is_iterable()` check would be even better

Comment (davidyell) [reply src/Model/Behavior/DuplicatableBehavior.php]: That would make the minimum PHP version for the plugin 7.1.0 is that okay? I don't see a PHP version constraint in the `composer.json` file, and it stipulates CakePHP 3.5 which would be PHP 5.6

Comment (ADmad) [reply src/Model/Behavior/DuplicatableBehavior.php]: Oh right, in that case is_array() and instanceof Traversable check then.

File: src/Model/Behavior/DuplicatableBehavior.php [hunk 2]
```diff
@@ -266,8 +266,10 @@ protected function _drillDownEntity($action, EntityInterface $entity, array $par
             return;
         }
 
-        foreach ($entity->{$prop} as $key => $e) {
-            $this->_drillDownEntity($action, $e, $parts, $value);
+        if (is_array($entity->{$prop}) || $entity->{$prop} instanceof \Traversable) {
+            foreach ($entity->{$prop} as $key => $e) {
```
Comment (ADmad) [inline src/Model/Behavior/DuplicatableBehavior.php]: The $key isn't necessary

Comment (davidyell) [reply src/Model/Behavior/DuplicatableBehavior.php]: I didn't add it, so feel that changing it is outside the scope of this PR

File: tests/TestCase/Model/Behavior/DuplicatableBehaviorTest.php [hunk 3]
```diff
@@ -229,4 +230,20 @@ public function testPreserveJoinData()
...
+     * Test that an entity with optionally null association can have fields removed when being duplicated
+     *
+     * @return void
+     */
+    public function testDuplicateWithRemoveOnNullAssociations()
+    {
+        $this->Invoices->behaviors()->get('Duplicatable')->setConfig('remove', ['invoice_data.data']);
+
+        $result = $this->Invoices->duplicate(3);
+        $this->assertInstanceOf('Cake\Datasource\EntityInterface', $result);
```
Comment (ADmad) [inline tests/TestCase/Model/Behavior/DuplicatableBehaviorTest.php]: Use `EntityInterface::class` instead of string.

**Comment by ADmad** [comment]
> Let me know if you want me to fix the PHPCS issues with the files or not

phpcs failures in `InvoicesFixture` are caused by your changes.

**Comment by davidyell** [comment]
Just for clarity, the existing fixture would have failed PHPCS because of the new trailing comma rule, which is why I asked, as it would have been outside of the pull requests scope.

**Comment by davidyell** [comment]
If you need some more changes, please do just amend the pull request 👍
